name: Deploy Databricks Bundle
 
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
 
jobs:
  deploy_dev:
    name: "Deploy to Dev"
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: .
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Install Dependencies
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel

      - name: Set HOME variable
        run: echo "HOME=/home/github-runner" >> $GITHUB_ENV
 
      - name: Validate Databricks Bundle (Dev)
        run: |
          python3 --version
          echo " Logging in to Azure..."
          az login --service-principal \
            --username "${{ secrets.DATABRICKS_CLIENT_ID }}" \
            --password "${{ secrets.DATABRICKS_CLIENT_SECRET }}" \
            --tenant "6d2c7112-af95-4e9e-acd6-d2a990e40851" \
            --allow-no-subscriptions
          
          # Get access token
          echo " Fetching Azure Access Token..."
          accessToken=$(az account get-access-token \
            --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d \
            --query accessToken \
            --output tsv)
          
          # Configure Databricks CLI auth
          echo " Setting up Databricks Auth..."
          export DATABRICKS_ACCESS_TOKEN="$accessToken"
          echo "Starting Databricks Validation (Dev)..."
          databricks bundle validate -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_BUNDLE_ENV: dev
 
      - name: Deploy Databricks Bundle (Dev)
        run: |
          echo "Starting Databricks Deployment (Dev)..."
          databricks bundle deploy -t dev --auto-approve
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEV }}
          DATABRICKS_BUNDLE_ENV: dev
 
  deploy_prod:
    name: "Deploy to Prod"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: .
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Install Dependencies
        run: |
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel
 
      - name: Set HOME variable
        run: echo "HOME=/home/github-runner" >> $GITHUB_ENV
 
      - name: Validate Databricks Bundle (Prod)
        run: |
          python3 --version
          echo " Logging in to Azure..."
          az login --service-principal \
            --username "${{ secrets.DATABRICKS_CLIENT_ID }}" \
            --password "${{ secrets.DATABRICKS_CLIENT_SECRET }}" \
            --tenant "6d2c7112-af95-4e9e-acd6-d2a990e40851" \
            --allow-no-subscriptions
          
          # Get access token
          echo " Fetching Azure Access Token..."
          accessToken=$(az account get-access-token \
            --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d \
            --query accessToken \
            --output tsv)
          
          # Configure Databricks CLI auth
          echo " Setting up Databricks Auth..."
          export DATABRICKS_ACCESS_TOKEN="$accessToken"
          
          echo "Starting Databricks Validation (Prod)..."
          databricks bundle validate -t prod 
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_BUNDLE_ENV: prod
 
      - name: Deploy Databricks Bundle (Prod)
        run: |
          echo "Starting Databricks Deployment (Prod)..."
          databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_BUNDLE_ENV: prod


