name: Deploy Databricks Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libyaml-dev build-essential

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel

      - name: Install Databricks Bundle (prebuilt wheels only)
        run: |
          pip install --only-binary=:all: databricks-bundle

      - name: Validate Databricks Bundle
        run: |
          databricks bundle validate -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

      - name: Deploy Databricks Bundle
        run: |
          databricks bundle deploy -t prod --auto-approve
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
