name: Deploy Databricks Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"   # Use quotes to prevent YAML from interpreting as 3.1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install databricks-bundle

      - name: Configure Databricks PAT
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_PAT }}" >> $GITHUB_ENV

      - name: Validate Databricks Bundle
        run: |
          python --version
          databricks bundle validate -t dev

      - name: Deploy Databricks Bundle
        run: |
          databricks bundle deploy -t dev --auto-approve
