name: Deploy Databricks Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main  # single branch deployment

jobs:
  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel

      - name: Install dependencies
        run: |
          pip install --no-build-isolation pyyaml==5.4.1
          pip install databricks-bundle

      - name: Validate Databricks Bundle
        run: |
          echo "Starting validation..."
          databricks bundle validate -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

      - name: Deploy Databricks Bundle
        run: |
          echo "Starting deployment..."
          databricks bundle deploy -t prod --auto-approve
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
