name: Deploy Databricks Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  deploy_dev:
    name: Deploy to Dev
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel databricks-bundle

      - name: Configure Databricks CLI with PAT
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_DEV }}" >> $GITHUB_ENV
          echo "DATABRICKS_ACCESS_TOKEN=${{ secrets.DATABRICKS_PAT_DEV }}" >> $GITHUB_ENV
          echo "DATABRICKS_BUNDLE_ENV=dev" >> $GITHUB_ENV

      - name: Validate Databricks Bundle (Dev)
        run: databricks bundle validate -t dev

      - name: Deploy Databricks Bundle (Dev)
        run: databricks bundle deploy -t dev --auto-approve

  deploy_prod:
    name: Deploy to Prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel databricks-bundle

      - name: Configure Databricks CLI with PAT
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_PROD }}" >> $GITHUB_ENV
          echo "DATABRICKS_ACCESS_TOKEN=${{ secrets.DATABRICKS_PAT_PROD }}" >> $GITHUB_ENV
          echo "DATABRICKS_BUNDLE_ENV=prod" >> $GITHUB_ENV

      - name: Validate Databricks Bundle (Prod)
        run: databricks bundle validate -t prod

      - name: Deploy Databricks Bundle (Prod)
        run: databricks bundle deploy -t prod
