name: Deploy Databricks Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Bundle
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev libffi-dev libssl-dev

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel cython

      - name: Install Databricks Bundle
        run: pip install databricks-bundle

      - name: Validate Bundle
        run: databricks bundle validate -t deployment
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
          DATABRICKS_BUNDLE_ENV: deployment

      - name: Deploy Bundle
        run: databricks bundle deploy -t deployment --auto-approve
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
          DATABRICKS_BUNDLE_ENV: deployment
